kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            max-pods: "150"
    extraPortMappings:
      - containerPort: 30181
        hostPort: 8081
        protocol: TCP
      - containerPort: 30923
        hostPort: 9123
        protocol: TCP
      - containerPort: 30924
        hostPort: 9124
        protocol: TCP
  - role: worker
  - role: worker
